### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by Moriand** [JoshMayberry/GUI_Maker#1]
Hi, can you say what I need to make it work ?, for example, python version

**Comment by JoshMayberry** [comment]
Hello there. :) 
I am using python 3.6.4

The idea of this package is to let you create a GUI in as few lines of code as possible.
It is still under heavy development, so syntax and stuff might change. But, feel free to use it and provide feedback. Once I am satisfied with how the module is set up, I will get it working properly on pip, but for now there are a few hoops you will have to jump through to get it on your system.

**REQUIRED MODULES**
The current modules that need to be installed are wxPython, pillow, pypubsub, and objectlistview.
These can be installed using pip. This is how I use pip:
```
py -m pip install wxPython
py -m pip install pillow
py -m pip install pypubsub
py -m pip install objectlistview
```

**INSTALLING GUI_MAKER**
I think that I have GUI_Maker on pip, so you can try 'py -m pip install GUI_Maker', but you might need to download this repository and either:
(A) Have it in the same folder as your program, 
(B) Add where you download it to your PATH variable, or
(C) Create a .pth file in the folder `Python36-32/Lib/site-packages` that shows where you downloaded the module to [click here for more info](https://docs.python.org/3/library/site.html).
I use option C right now.

**TESTING INSTALATION**
Once you have the required modules installed and GUI_Maker on your system, you can make sure it works by going to the folder `GUI_Maker` and [shift]+[right click] on the folder `examples`. Select `Open command window here` from the popup list, and a black cmd window will appear.
Type: `py GUI_Example_LayoutControl.py` and press [enter].
If a window popped up that says "Lorem Ipsum" in it, then it worked! You have it installed correctly.

**USING GUI_MAKER**
Now, you should be able to create user interfaces using this template:

```
import GUI_Maker
gui = GUI_Maker.build()

def testFunction(event):
    print("You ran a function from a GUI!")
    event.Skip()

with gui.addWindow(title = "Template") as myFrame:
    myFrame.addButton("Run Me", myFunction = testFunction)
    myFrame.showWindow()

gui.finish()
```

Until I get some proper documentation created, you will have to use the doc strings that accompany each function.

I hope that this helps you out. I did not think anyone would be using my package so soon. I can try to expedite the documentation process for you if you need it though.
